### ISSUE TITLE
will socket be supported?

### ISSUE THREAD

**Issue by airk000** [dart-io-packages/universal_io#3]
As the title mentioned. I just want use WebSocket in Flutter web application, as we know, `dart:html` can not be used in Flutter SDK. So guys, I'm counting on you

**Comment by terrier989** [comment]
Perhaps [web_socket_channel](https://pub.dev/packages/web_socket_channel) could solve your issue?

**Comment by airk000** [comment]
I'll try it and then post the result here, thank u!

**Comment by airk000** [comment]
The answer is NO! 

`WebSocketChannel` 's constructor need a connected StreamChannel which must be already handshaked. Then `IOWebSocketChannel` impled by `dart:io` which is not supported on flutter web you know. And the last one `HtmlWebSocketChannel` impled by `dart:html` which is not include in flutter sdk.

So, I really can't figure it out.

**Comment by airk000** [comment]
I'm working on porting the _WebSocketImpl stuff code, based on THIS library (need the HttpClient), I'll left the result here later.
